services:
  nibiru-chat-api:
    build:
      context: .
    container_name: nibiru-chat-api
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - .env
    command: sh -c "npm run migrate up && npm run start"
